# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Dala/Documents/bezier/libs/realtime/ext/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Dala/Documents/bezier/libs/realtime/ext/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Dala/Documents/bezier/libs/realtime/ext/glfw/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Dala/Documents/bezier/libs/realtime/ext/glfw/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/Dala/Documents/bezier/libs/realtime/ext/glfw/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.15/Modules/WriteBasicConfigVersionFile.cmake))

/Users/Dala/Documents/bezier/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/Dala/Documents/bezier -B/Users/Dala/Documents/bezier
